export const metadata = [
  { path: "game/ovo", title: "OvO | Cosmic City" },
  { path: "game/ovo-2", title: "OvO 2 | Cosmic City" },
  { path: "game/1v1-lol", title: "1v1.LOL | Cosmic City" },
  { path: "game/justfall-lol", title: "JustFall.LOL | Cosmic City" },
  { path: "game/cluster-rush", title: "Cluster Rush | Cosmic City" },
  { path: "game/bottle-flip-3d", title: "Bottle Flip 3D | Cosmic City" },
  { path: "game/2048", title: "2048 | Cosmic City" },
  { path: "game/stickman-hook", title: "Stickman Hook | Cosmic City" },
  { path: "game/drift-hunters", title: "Drift Hunters | Cosmic City" },
  { path: "game/basketball-stars", title: "Basketball Stars | Cosmic City" },
  { path: "game/run-3", title: "Run 3 | Cosmic City" },
  { path: "game/cookie-clicker", title: "Cookie Clicker | Cosmic City" },
  { path: "game/slope", title: "Slope | Cosmic City" },
  { path: "game/slope-3", title: "Slope 3 | Cosmic City" },
  {
    path: "game/worlds-hardest-game-3",
    title: "World's Hardest Game 3 | Cosmic City",
  },
  {
    path: "game/friday-night-funkin",
    title: "Friday Night Funkin' | Cosmic City",
  },
  { path: "game/mr-bullet", title: "Mr Bullet | Cosmic City" },
  { path: "game/among-us", title: "Among Us | Cosmic City" },
  { path: "game/moto-x3m", title: "Moto X3M | Cosmic City" },
  { path: "game/bitlife", title: "BitLife | Cosmic City" },
  { path: "game/color-switch", title: "Color Switch | Cosmic City" },
  { path: "game/google-snake", title: "Google Snake | Cosmic City" },
  { path: "game/color-road", title: "Color Road | Cosmic City" },
  { path: "game/flappy-bird", title: "Flappy Bird | Cosmic City" },
  { path: "game/paper-io-2", title: "Paper.io 2 | Cosmic City" },
  { path: "game/fnaf-2", title: "FNAF 2 | Cosmic City" },
  { path: "game/fnaf-3", title: "FNAF 3 | Cosmic City" },
  { path: "game/fnaf-4", title: "FNAF 4 | Cosmic City" },
  { path: "game/subway-surfers", title: "Subway Surfers | Cosmic City" },
  { path: "game/vex-6", title: "Vex 6 | Cosmic City" },
  { path: "game/funny-shooter-2", title: "Funny Shooter 2 | Cosmic City" },
  { path: "game/geometry-dash", title: "Geometery Dash | Cosmic City" },
  { path: "game/drive-mad", title: "Drive Mad | Cosmic City" },
  { path: "game/swingo", title: "Swingo | Cosmic City" },
  { path: "game/tag", title: "Tag | Cosmic City" },
  { path: "game/jetpack-joyride", title: "Jetpack Joyride | Cosmic City" },
  { path: "/", title: "Cosmic City" },
  { path: "games", title: "Cosmic City | Games" },
  { path: "socials", title: "Cosmic City | Socials" },
  { path: "*", title: "404" },
];
