export const metadata = [
  { path: "game/ovo", title: "OvO | Cosmic City" },
  { path: "game/ovo-2", title: "OvO 2 | Cosmic City" },
  { path: "game/ovo-3", title: "OvO 3 | Cosmic City" },
  { path: "game/1v1-lol", title: "1v1.LOL | Cosmic City" },
  { path: "game/justfall-lol", title: "JustFall.LOL | Cosmic City" },
  { path: "game/cluster-rush", title: "Cluster Rush | Cosmic City" },
  { path: "game/duck-life-3", title: "Duck Life 3 | Cosmic City" },
  { path: "game/duck-life-4", title: "Duck Life 4 | Cosmic City" },
  { path: "game/bottle-flip-3d", title: "Bottle Flip 3D | Cosmic City" },
  { path: "game/2048", title: "2048 | Cosmic City" },
  { path: "game/superhot", title: "Superhot | Cosmic City" },
  { path: "game/stickmerge", title: "Stickmerge | Cosmic City" },
  { path: "game/there-is-no-game", title: "There Is No Game | Cosmic City" },
  { path: "game/stickman-hook", title: "Stickman Hook | Cosmic City" },
  { path: "game/gimme-the-airpod", title: "Gimme The Airpod | Cosmic City" },
  { path: "game/learn-to-fly", title: "Learn To Fly | Cosmic City" },
  { path: "game/learn-to-fly-2", title: "Learn To Fly 2 | Cosmic City" },
  { path: "game/tiny-fishing", title: "Tiny Fishing | Cosmic City" },
  { path: "game/n-gon", title: "n-gon | Cosmic City" },
  { path: "game/ducklings-io", title: "Ducklings.io | Cosmic City" },
  { path: "game/drift-hunters", title: "Drift Hunters | Cosmic City" },
  { path: "game/monkey-mart", title: "Monkey Mart | Cosmic City" },
  { path: "game/basketball-stars", title: "Basketball Stars | Cosmic City" },
  { path: "game/stair-race-3d", title: "Stair Race 3D | Cosmic City" },
  { path: "game/crossy-road", title: "Crossy Road | Cosmic City" },
  { path: "game/stack", title: "Stack | Cosmic City" },
  { path: "game/blumgi-rocket", title: "Blumgi Rocket | Cosmic City" },
  { path: "game/tunnel-rush", title: "Tunnel Rush | Cosmic City" },
  { path: "game/run-3", title: "Run 3 | Cosmic City" },
  { path: "game/cookie-clicker", title: "Cookie Clicker | Cosmic City" },
  { path: "game/slope", title: "Slope | Cosmic City" },
  { path: "game/slope-3", title: "Slope 3 | Cosmic City" },
  {
    path: "game/worlds-hardest-game-3",
    title: "World's Hardest Game 3 | Cosmic City",
  },
  {
    path: "game/friday-night-funkin",
    title: "Friday Night Funkin' | Cosmic City",
  },
  { path: "game/mr-bullet", title: "Mr Bullet | Cosmic City" },
  { path: "game/among-us", title: "Among Us | Cosmic City" },
  { path: "game/moto-x3m", title: "Moto X3M | Cosmic City" },
  { path: "game/bitlife", title: "BitLife | Cosmic City" },
  { path: "game/color-switch", title: "Color Switch | Cosmic City" },
  { path: "game/google-snake", title: "Google Snake | Cosmic City" },
  { path: "game/color-road", title: "Color Road | Cosmic City" },
  { path: "game/flappy-bird", title: "Flappy Bird | Cosmic City" },
  { path: "game/paper-io-2", title: "Paper.io 2 | Cosmic City" },
  { path: "game/fnaf-2", title: "FNAF 2 | Cosmic City" },
  { path: "game/fnaf-3", title: "FNAF 3 | Cosmic City" },
  { path: "game/fnaf-4", title: "FNAF 4 | Cosmic City" },
  { path: "game/subway-surfers", title: "Subway Surfers | Cosmic City" },
  { path: "game/vex-6", title: "Vex 6 | Cosmic City" },
  { path: "game/funny-shooter-2", title: "Funny Shooter 2 | Cosmic City" },
  { path: "game/geometry-dash", title: "Geometery Dash | Cosmic City" },
  { path: "game/drive-mad", title: "Drive Mad | Cosmic City" },
  { path: "game/swingo", title: "Swingo | Cosmic City" },
  { path: "game/tag", title: "Tag | Cosmic City" },
  { path: "game/jetpack-joyride", title: "Jetpack Joyride | Cosmic City" },
  { path: "game/karlsont", title: "Karlson't | Cosmic City" },
  { path: "game/getaway-shootout", title: "Getaway Shootout | Cosmic City" },
  { path: "game/rooftop-snipers", title: "Rooftop Snipers | Cosmic City" },
  { path: "game/rooftop-snipers-2", title: "Rooftop Snipers 2 | Cosmic City" },
  { path: "game/stickman-climb-2", title: "Stickman Climb 2 | Cosmic City" },
  {
    path: "game/game-inside-a-game",
    title: "Game inside A Game | Cosmic City",
  },
  {
    path: "game/big-tower-tiny-square",
    title: "Big Tower Tiny Square | Cosmic City",
  },
  {
    path: "game/big-flappy-tower-tiny-square",
    title: "Big Flappy Tower Tiny Square | Cosmic City",
  },
  { path: "game/hexgl", title: "HexGL | Cosmic City" },
  { path: "game/doodle-jump", title: "Doodle Jump | Cosmic City" },
  { path: "game/bullet-bros", title: "Bullet Bros | Cosmic City" },
  { path: "game/yohoho-io", title: "YoHoHo.io | Cosmic City" },
  { path: "game/burrito-bison", title: "Burrito Bison | Cosmic City" },
  { path: "game/sketchbook-04", title: "Sketchbook 0.4 | Cosmic City" },
  { path: "game/g-switch-3", title: "G Switch 3 | Cosmic City" },
  { path: "game/g-switch-4", title: "G Switch 4 | Cosmic City" },
  { path: "game/flip-bros", title: "Flip Bros | Cosmic City" },
  { path: "game/space-thing", title: "Space Thing | Cosmic City" },
  { path: "game/flip-runner", title: "Flip Runner | Cosmic City" },
  { path: "game/digging-master", title: "Digging Master | Cosmic City" },
  { path: "game/gunspin", title: "Gunspin | Cosmic City" },
  { path: "game/stick-defenders", title: "Stick Defenders | Cosmic City" },
  { path: "game/gobble", title: "Gobble | Cosmic City" },
  { path: "game/masked-forces", title: "Masked Forces | Cosmic City" },
  { path: "game/minecraft", title: "Minecraft | Cosmic City" },
  { path: "game/backrooms", title: "Backrooms | Cosmic City" },
  { path: "game/big-red-button", title: "Big Red Button | Cosmic City" },
  { path: "game/death-run-3d", title: "Death Run 3D | Cosmic City" },
  { path: "game/doge-miner", title: "Doge Miner | Cosmic City" },
  { path: "game/snow-rider-3d", title: "Snow Rider 3D | Cosmic City" },
  { path: "game/circloo", title: "circloO | Cosmic City" },
  { path: "game/cell-machine", title: "Cell Machine | Cosmic City" },
  { path: "game/rocket-pult", title: "Rocket Pult | Cosmic City" },
  { path: "game/snow-battle-io", title: "SnowBattle.io | Cosmic City" },
  { path: "game/fruit-ninja", title: "Fruit Ninja | Cosmic City" },
  { path: "game/temple-run-2", title: "Temple Run 2 | Cosmic City" },
  { path: "game/uno", title: "UNO | Cosmic City" },
  { path: "game/poor-eddie", title: "Poor Eddie | Cosmic City" },
  { path: "game/brain-test", title: "Brain Test | Cosmic City" },
  { path: "/", title: "Cosmic City" },
  { path: "games", title: "Cosmic City | Games" },
  { path: "socials", title: "Cosmic City | Socials" },
  { path: "*", title: "404" },
];
